-- MySQL Script generated by MySQL Workbench
-- Thu Dec  6 21:25:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbFraccion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbFraccion` ;

-- -----------------------------------------------------
-- Schema dbFraccion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbFraccion` DEFAULT CHARACTER SET utf8 ;
USE `dbFraccion` ;

-- -----------------------------------------------------
-- Table `dbFraccion`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `contrasena` VARCHAR(255) NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `desactivado` TINYINT(1) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblUsuario_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`caracteristicas_financieras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`caracteristicas_financieras` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`caracteristicas_financieras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `rentabilidad_anual` DOUBLE UNSIGNED NULL,
  `rentabilidad_mensual` DOUBLE UNSIGNED NULL,
  `plazo_meses` INT UNSIGNED NULL,
  `objetivo_financiacion` DOUBLE UNSIGNED NULL,
  `beneficio_operacion` DOUBLE UNSIGNED NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCaracteristicasFinancieras_UNIQUE` (`id` ASC),
  INDEX `fk_tblCaracteristicaFinanciera_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`estados` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`estados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `estado` VARCHAR(20) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblEstado_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`ciudades` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`ciudades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `codigo` VARCHAR(10) NULL,
  `nombre` VARCHAR(100) NULL,
  `departamento` VARCHAR(100) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCiudad_UNIQUE` (`id` ASC),
  INDEX `fk_tblCiudad_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`tipos_identificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`tipos_identificaciones` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`tipos_identificaciones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `nombre_recortado` VARCHAR(2) NULL,
  `url` VARCHAR(250) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTipoIdentificacion_UNIQUE` (`id` ASC),
  INDEX `fk_tblTipoIdentificacion_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`aliados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`aliados` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`aliados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `identificacion` VARCHAR(20) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(250) NULL,
  `ciudades_id` INT UNSIGNED NOT NULL,
  `tipos_identificaciones_id` INT UNSIGNED NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblAliado_tblCiudad1_idx` (`ciudades_id` ASC),
  INDEX `fk_tblAliado_tblTipoIdentificacion1_idx` (`tipos_identificaciones_id` ASC),
  INDEX `fk_tblAliado_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`productos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `fecha_vencimiento` INT UNSIGNED NULL,
  `fecha_inicio` INT UNSIGNED NULL,
  `maxima_inversion` DOUBLE UNSIGNED NULL,
  `minima_inversion` DOUBLE UNSIGNED NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `maximo_inversionistas` INT UNSIGNED NULL,
  `minimo_inversionistas` INT UNSIGNED NULL,
  `caracteristicas_financieras_id` INT UNSIGNED NOT NULL,
  `estados_id` INT UNSIGNED NOT NULL,
  `aliados_id` INT UNSIGNED NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idProducto_UNIQUE` (`id` ASC),
  INDEX `fk_tblProducto_tblCaracteristicasFinancieras_idx` (`caracteristicas_financieras_id` ASC),
  INDEX `fk_tblProducto_tblEstado1_idx` (`estados_id` ASC),
  INDEX `fk_tblProducto_tblAliado1_idx` (`aliados_id` ASC),
  INDEX `fk_tblProducto_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`tipos_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`tipos_productos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`tipos_productos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(100) NULL,
  `productos_id` INT NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTipoProducto_UNIQUE` (`id` ASC),
  INDEX `fk_tblTipoProducto_tblProducto1_idx` (`productos_id` ASC),
  INDEX `fk_tblTipoProducto_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`caracteristicas_tecnicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`caracteristicas_tecnicas` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`caracteristicas_tecnicas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `visible` TINYINT(1) NULL,
  `orden` INT NULL,
  `productos_id` INT NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCaracteristicasTecnicas_UNIQUE` (`id` ASC),
  INDEX `fk_tblCaracteristicasTecnicas_tblProducto1_idx` (`productos_id` ASC),
  INDEX `fk_tblCaracteristicaTecnica_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`tipo_contenidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`tipo_contenidos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`tipo_contenidos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTipoContenido_UNIQUE` (`id` ASC),
  INDEX `fk_tipo_contenidos_usuarios1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`contenidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`contenidos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`contenidos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_tiempo_actualizacion` INT(128) UNSIGNED NOT NULL,
  `ubicacion` VARCHAR(100) NULL,
  `nombre_archivo` VARCHAR(45) NULL,
  `extension` VARCHAR(45) NULL,
  `tamanio` DOUBLE NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  `tipo_contenidos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtImagenes_UNIQUE` (`id` ASC),
  INDEX `fk_tblImagen_tblUsuario1_idx` (`usuarios_id` ASC),
  INDEX `fk_contenidos_tipo_contenidos1_idx` (`tipo_contenidos_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`aliados_contenidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`aliados_contenidos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`aliados_contenidos` (
  `contenidos_id` INT UNSIGNED NOT NULL,
  `aliados_id` INT UNSIGNED NOT NULL,
  INDEX `fk_tblImagen_Aliado_tblImagen1_idx` (`contenidos_id` ASC),
  INDEX `fk_tblImagen_Aliado_tblAliado1_idx` (`aliados_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`contenido_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`contenido_producto` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`contenido_producto` (
  `contenido_id` INT UNSIGNED NOT NULL,
  `producto_id` INT NOT NULL,
  INDEX `fk_tblProducto_Imagen_tblImagen1_idx` (`contenido_id` ASC),
  INDEX `fk_tblProducto_Imagen_tblProducto1_idx` (`producto_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`caracteristicas_contenidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`caracteristicas_contenidos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`caracteristicas_contenidos` (
  `caracteristicas_tecnicas_id` INT UNSIGNED NOT NULL,
  `contenidos_id` INT UNSIGNED NOT NULL,
  INDEX `fk_tblCaracteristica_Imagen_tblCaracteristicaTecnica1_idx` (`caracteristicas_tecnicas_id` ASC),
  INDEX `fk_tblCaracteristica_Imagen_tblImagen1_idx` (`contenidos_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`sesiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`sesiones` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`sesiones` (
  `id` VARCHAR(128) NOT NULL,
  `MarcaTiempoActualizacion` INT(10) NOT NULL,
  `Data` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`roles` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblRol_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`generos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`generos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idGenero_UNIQUE` (`id` ASC),
  INDEX `fk_tblGenero_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`tipos_personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`tipos_personas` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`tipos_personas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblTipoPersona_tblUsuario1_idx` (`usuarios_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`personas` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`personas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(150) NULL,
  `Correo` VARCHAR(50) NULL,
  `Telefono` VARCHAR(20) NULL,
  `Identificacion` VARCHAR(20) NULL,
  `Celular` VARCHAR(20) NULL,
  `Ocupacion` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(255) NULL,
  `FechaNacimiento` VARCHAR(15) NULL,
  `Hijos` INT UNSIGNED NULL,
  `PersonasACargo` INT UNSIGNED NULL,
  `tipos_identificaciones_id` INT UNSIGNED NOT NULL,
  `ciudades_id` INT UNSIGNED NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  `personas_referido_id` INT UNSIGNED NULL,
  `generos_id` INT UNSIGNED NOT NULL,
  `tipos_personas_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idPersona_UNIQUE` (`id` ASC),
  INDEX `fk_tblPersona_tblTipoIdentificacion1_idx` (`tipos_identificaciones_id` ASC),
  INDEX `fk_tblPersona_tblCiudad1_idx` (`ciudades_id` ASC),
  INDEX `fk_tblPersona_tblUsuario1_idx` (`usuarios_id` ASC),
  INDEX `fk_tblPersona_tblPersona1_idx` (`personas_referido_id` ASC),
  INDEX `fk_tblPersona_tblGenero1_idx` (`generos_id` ASC),
  INDEX `fk_personas_tipos_personas1_idx` (`tipos_personas_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`estados_inversiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`estados_inversiones` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`estados_inversiones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idEstado_Inversion_UNIQUE` (`id` ASC),
  INDEX `fk_tblEstado_Inversion_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`personas_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`personas_productos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`personas_productos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FechaInversion` INT UNSIGNED NOT NULL,
  `Inversion` DOUBLE UNSIGNED NULL,
  `Rentabilidad` DOUBLE UNSIGNED NULL,
  `personas_id` INT UNSIGNED NOT NULL,
  `productos_id` INT NOT NULL,
  `estados_inversiones_id` INT UNSIGNED NOT NULL,
  INDEX `fk_tblPersona_Producto_tblPersona1_idx` (`personas_id` ASC),
  INDEX `fk_tblPersona_Producto_tblProducto1_idx` (`productos_id` ASC),
  INDEX `fk_tblPersona_Producto_tblEstado_Inversion1_idx` (`estados_inversiones_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idPersona_Producto_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`estados_civiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`estados_civiles` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`estados_civiles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idEstadoCivil_UNIQUE` (`id` ASC),
  INDEX `fk_tblEstadoCivil_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`rubros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`rubros` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`rubros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idConcepto_UNIQUE` (`id` ASC),
  INDEX `fk_tblRubro_tblUsuario1_idx` (`usuarios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`medios_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`medios_pagos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`medios_pagos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblMedioPago_tblUsuario1_idx` (`usuarios_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`estados_cuentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`estados_cuentas` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`estados_cuentas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MarcaTiempoActualizacion` INT UNSIGNED NOT NULL,
  `FechaTransaccion` INT NULL,
  `Valor` DOUBLE UNSIGNED NULL,
  `personas_productos_id` INT UNSIGNED NOT NULL,
  `rubros_id` INT UNSIGNED NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  `medios_pagos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idEstadoCuenta_UNIQUE` (`id` ASC),
  INDEX `fk_tblEstadoCuenta_tblPersona_Producto1_idx` (`personas_productos_id` ASC),
  INDEX `fk_tblEstadoCuenta_tblRubro1_idx` (`rubros_id` ASC),
  INDEX `fk_tblEstadoCuenta_tblUsuario1_idx` (`usuarios_id` ASC),
  INDEX `fk_estados_cuentas_medios_pagos1_idx` (`medios_pagos_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`formularios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`formularios` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`formularios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`tipos_campos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`tipos_campos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`tipos_campos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`campos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`campos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`campos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `tipos_campos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_campos_tipos_campos1_idx` (`tipos_campos_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`formularios_campos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`formularios_campos` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`formularios_campos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Orden` INT NULL,
  `Requerido` TINYINT(1) NULL,
  `formularios_id` INT UNSIGNED NOT NULL,
  `campos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_formularios_campos_formularios1_idx` (`formularios_id` ASC),
  INDEX `fk_formularios_campos_campos1_idx` (`campos_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`personas_formularios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`personas_formularios` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`personas_formularios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FechaCreacion` INT NULL,
  `personas_id` INT UNSIGNED NOT NULL,
  `formularios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_personas_formularios_personas1_idx` (`personas_id` ASC),
  INDEX `fk_personas_formularios_formularios1_idx` (`formularios_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`respuestas_formularios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`respuestas_formularios` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`respuestas_formularios` (
  `id` INT NOT NULL,
  `Valor` TEXT NULL,
  `formularios_campos_id` INT UNSIGNED NOT NULL,
  INDEX `fk_respuestas_formularios_formularios_campos1_idx` (`formularios_campos_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`opciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`opciones` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`opciones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFraccion`.`campos_opciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbFraccion`.`campos_opciones` ;

CREATE TABLE IF NOT EXISTS `dbFraccion`.`campos_opciones` (
  `campos_id` INT UNSIGNED NOT NULL,
  `opciones_id` INT UNSIGNED NOT NULL,
  INDEX `fk_campos_opciones_campos1_idx` (`campos_id` ASC),
  INDEX `fk_campos_opciones_opciones1_idx` (`opciones_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dbFraccion`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbFraccion`;
INSERT INTO `dbFraccion`.`usuarios` (`id`, `marca_tiempo_actualizacion`, `nombre`, `contrasena`, `nombre_usuario`, `desactivado`, `usuarios_id`) VALUES (1, 1543309200, 'root', '.Fraccion*2018', 'root', 0, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbFraccion`.`estados`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbFraccion`;
INSERT INTO `dbFraccion`.`estados` (`id`, `marca_tiempo_actualizacion`, `estado`, `usuarios_id`) VALUES (1, 1543309200, 'Activo', 1);
INSERT INTO `dbFraccion`.`estados` (`id`, `marca_tiempo_actualizacion`, `estado`, `usuarios_id`) VALUES (2, 1543309200, 'Inactivo', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbFraccion`.`ciudades`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbFraccion`;
INSERT INTO `dbFraccion`.`ciudades` (`id`, `marca_tiempo_actualizacion`, `codigo`, `nombre`, `departamento`, `usuarios_id`) VALUES (1, 1543309200, '54001', 'Cúcuta', 'Norte de Santander', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbFraccion`.`tipos_identificaciones`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbFraccion`;
INSERT INTO `dbFraccion`.`tipos_identificaciones` (`id`, `marca_tiempo_actualizacion`, `nombre`, `nombre_recortado`, `url`, `usuarios_id`) VALUES (1, 1543309200, 'Cédula Ciudadania', 'CC', NULL, 1);
INSERT INTO `dbFraccion`.`tipos_identificaciones` (`id`, `marca_tiempo_actualizacion`, `nombre`, `nombre_recortado`, `url`, `usuarios_id`) VALUES (2, 1543309200, 'Pasaporte', 'PP', NULL, 1);
INSERT INTO `dbFraccion`.`tipos_identificaciones` (`id`, `marca_tiempo_actualizacion`, `nombre`, `nombre_recortado`, `url`, `usuarios_id`) VALUES (3, 1543309200, 'Cédula extranjería', 'CE', NULL, 1);
INSERT INTO `dbFraccion`.`tipos_identificaciones` (`id`, `marca_tiempo_actualizacion`, `nombre`, `nombre_recortado`, `url`, `usuarios_id`) VALUES (4, 1543309200, 'NIT', 'NN', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbFraccion`.`aliados`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbFraccion`;
INSERT INTO `dbFraccion`.`aliados` (`id`, `marca_tiempo_actualizacion`, `nombre`, `identificacion`, `telefono`, `direccion`, `ciudades_id`, `tipos_identificaciones_id`, `usuarios_id`) VALUES (1, 1543309200, 'Celeus Group', '123456', '3333333', 'Cll 13 a # 1E-87 Barrio Caobos', 1, 4, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbFraccion`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbFraccion`;
INSERT INTO `dbFraccion`.`roles` (`id`, `MarcaTiempoActualizacion`, `Nombre`, `Descripcion`, `usuarios_id`) VALUES (1, 1543309200, 'Administrador', 'Usuario Administrador de sitio', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbFraccion`.`tipos_personas`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbFraccion`;
INSERT INTO `dbFraccion`.`tipos_personas` (`id`, `MarcaTiempoActualizacion`, `Nombre`, `Descripcion`, `usuarios_id`) VALUES (1, 1543309200, 'Prospecto', 'Prospecto', 1);
INSERT INTO `dbFraccion`.`tipos_personas` (`id`, `MarcaTiempoActualizacion`, `Nombre`, `Descripcion`, `usuarios_id`) VALUES (2, 1543309200, 'Inversionista', 'Inversionista', 1);
INSERT INTO `dbFraccion`.`tipos_personas` (`id`, `MarcaTiempoActualizacion`, `Nombre`, `Descripcion`, `usuarios_id`) VALUES (3, 1543309200, 'Visitante', 'Visitante', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbFraccion`.`estados_inversiones`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbFraccion`;
INSERT INTO `dbFraccion`.`estados_inversiones` (`id`, `MarcaTiempoActualizacion`, `Nombre`, `usuarios_id`) VALUES (1, 1543309200, 'Activo', 1);
INSERT INTO `dbFraccion`.`estados_inversiones` (`id`, `MarcaTiempoActualizacion`, `Nombre`, `usuarios_id`) VALUES (2, 1543309200, 'Desistido', 1);

COMMIT;

